
exclude:
  - "/vendor/"
  - "/node_modules/"
  - "/assets/_src_img/"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: The Nomadic Ashram
subtitle: "How is your Inner Fire"
description: Hatha Yoga Master with 25 years of Yoga experience; diplomas in Dru Yoga, Transformational Yoga, Ayurvedic Yoga Therapy and Thai Yoga Massage
url: "https://nomadic-ashram.netlify.com" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: "http://localhost:3000"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Sass is off loaded to gulp.js 
# sass:
#     sass_dir: assets/_scss
#     style: compressed

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

collections:
  adventures:
    output: true
  pages:
    output: true
  posts:
    output: true

public_folder: /uploads
media_folder: /uploads

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page-standard"
  - scope:
      path: ""
      type: "adventures"
    values:
      layout: "adventure"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

