backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "adventures" # Used in routes, e.g. /admin/collections/blog
    label: "Adventures" # Used in the UI
    folder: "_adventures" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "adventure"}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Deposit", name: "deposit", widget: "number"}
      - {label: "Total Places", name: "totalPlaces", widget: "number"}
      - {label: "Remaining Places", name: "remainingPlaces", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Dates
        name: dates
        widget: list
        fields:
          - {label: Date, name: date, widget: string}
          - {label: Description, name: description, widget: string}
      - label: Prices
        name: prices
        widget: list
        fields:
          - {label: Price, name: price, widget: string}
          - {label: Description, name: description, widget: string}

  - name: "pages" # Used in routes, e.g. /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      #- {label: "Layout", name: "layout", widget: "hidden", default: "adventure"}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Permalink", name: "permalink", widget: "string", hint: "Page URL e.g. /page-name/ (with slash at the end)"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "headerSubCopy", name: "subtitle", widget: "string", required: false}
      - {label: "metaDescription", name: "subtitle", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Global"
    name: "global"
    files:
      - label: "Business Info"
        name: "info"
        file: "_data/business.yml"
        fields:
          - {label: name, name: name, widget: string}
          - {label: address_full, name: address_full, widget: string, hint: "Example: 333 S. Franklin Street Tampa, FL 33602"}
          - {label: address_street, name: address_street, widget: string, hint: "Example: 333 S. Franklin Street"}
          - {label: address_city, name: address_city, widget: string, hint: "Tampa"}
          - {label: phone_primay, name: phone_primay, widget: string, hint: "(813) 123-4567"}
          - {label: phone_secondary, name: phone_secondary, widget: string, hint: "(813) 765-4321"}
          - {label: email_primary, name: email_primary, widget: string }
          - {label: google_maps_api_key, name: google_maps_api_key, widget: string, hint: "Used to display embeded maps"}
      - label: "Accreditations"
        name: "accreditations"
        file: "_data/accreditations.yml"
        fields:
          - label: Accreditations
            name: accreditations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Image, name: img, widget: image}
              - {label: Link, name: link, widget: string}
      - label: "Testimonials"
        name: "testimonials"
        file: "_data/testimonials.yml"
        fields:
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Location, name: location, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Image, name: img, widget: image}
      - label: "Menu"
        name: "menu"
        file: "_data/menu.yml"
        fields:
          - label: Menu
            name: menu
            widget: list
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Url, name: url, widget: string}
      - label: "Social Media"
        name: "social"
        file: "_data/social_media.yml"
        fields:
          - label: platform
            name: platform
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Link, name: link, widget: string}
  - label: "Home"
    name: "home"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - {label: Title, name: title, widget: string, hint: "The Large Text at the top"}
          - { label: Subtitle, name: headerSubCopy, widget: string }
          - { label: slider-image, name: slider-image, widget: image }
          - {label: Intro Title, name: intro-title, widget: string, hint: "The first chunk of content"}
          - {label: Intro Subtitle, name: intro-subtitle, widget: string, hint: "The first chunk of content"}
          - {label: Intro Body, name: intro-body, widget: markdown}
          - {label: Intro Image, name: intro-img, widget: image}
          - {label: Feature Image, name: feature-img, widget: image}
          - {label: Feature Title, name: feature-title, widget: string}
          - {label: Feature Subtitle, name: feature-subtitle, widget: string}
          - { label: Feature Link Text, name: feature-link-text, widget: string }
          - { label: Feature Link, name: feature-link, widget: string }
          - { label: Adventures Title, name: adventures-title, widget: string }
          - { label: Adventures Body, name: adventures-body, widget: string }
